services:
  # eventstore:
  #   image: eventstore/eventstore:24.2.0
  #   platform: linux/amd64
  #   container_name: eventstore
  #   environment:
  #     - EVENTSTORE_INSECURE=true
  #     - EVENTSTORE_RUN_PROJECTIONS=All
  #     - EVENTSTORE_START_STANDARD_PROJECTIONS=true
  #   ports:
  #     - "2113:2113"
  #     - "1113:1113"
  #   volumes:
  #     - eventstore-data:/var/lib/eventstore

  eventstore:
    image: eventstore/eventstore:24.10.7-alpha-arm64v8
    container_name: eventstore
    environment:
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_EXT_IP=0.0.0.0
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
    ports:
      - "2113:2113"
    volumes:
      - eventstore-data:/var/lib/eventstore

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: banking_read
      POSTGRES_USER: banking
      POSTGRES_PASSWORD: banking
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    container_name: keycloak
    command: [ "start-dev", "--http-port=8080" ]
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"

  account-service:
    build:
      context: .
      dockerfile: account-service/Dockerfile
    container_name: account-service
    depends_on:
      - postgres
      - redis
      - kafka
      - eventstore
      - keycloak
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/banking_read?stringtype=unspecified
      SPRING_DATASOURCE_USERNAME: banking
      SPRING_DATASOURCE_PASSWORD: banking
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EVENTSTORE_CONNECTION_STRING: esdb://eventstore:2113?tls=false
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/retail
      JAVA_TOOL_OPTIONS: -Duser.timezone=UTC
      TZ: UTC
    ports:
      - "8081:8081"

volumes:
  eventstore-data:
  postgres-data:
