services:
  # eventstore:
  #   image: eventstore/eventstore:24.2.0
  #   platform: linux/amd64
  #   container_name: eventstore
  #   environment:
  #     - EVENTSTORE_INSECURE=true
  #     - EVENTSTORE_RUN_PROJECTIONS=All
  #     - EVENTSTORE_START_STANDARD_PROJECTIONS=true
  #   ports:
  #     - "2113:2113"
  #     - "1113:1113"
  #   volumes:
  #     - eventstore-data:/var/lib/eventstore

  eventstore:
    image: eventstore/eventstore:24.10.7-alpha-arm64v8
    container_name: eventstore
    environment:
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_EXT_IP=0.0.0.0
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_ADVERTISE_HOST_TO_CLIENT_AS=127.0.0.1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
    ports:
      - "2113:2113"
    volumes:
      - eventstore-data:/var/lib/eventstore

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: banking_read
      POSTGRES_USER: banking
      POSTGRES_PASSWORD: banking
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  postgres-keycloak:
    image: postgres:16
    container_name: postgres-keycloak
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: strong_password
    ports:
      - "5433:5432"
    volumes:
      - postgres-keycloak-data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    container_name: keycloak
    command: start --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-keycloak:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: strong_password
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    depends_on:
      - postgres-keycloak

  account-service:
    build:
      context: .
      dockerfile: account-service/Dockerfile
    container_name: account-service
    depends_on:
      - postgres
      - redis
      - kafka
      - eventstore
      - keycloak
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/banking_read?stringtype=unspecified
      SPRING_DATASOURCE_USERNAME: banking
      SPRING_DATASOURCE_PASSWORD: banking
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EVENTSTORE_CONNECTION_STRING: esdb://eventstore:2113?tls=false
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://localhost:8080/realms/retail
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/retail/protocol/openid-connect/certs
      JAVA_TOOL_OPTIONS: -Duser.timezone=UTC
      TZ: UTC
    ports:
      - "8081:8081"

volumes:
  eventstore-data:
  postgres-data:
  postgres-keycloak-data:
